spring:
  application:
    name: spring-cloud-gateway

  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
          uri: http://localhost:8088
server:
  port: 8088
